### ISSUE TITLE
Emoticon checking still doesn't appear to work

### ISSUE THREAD

**Issue by christian-mann** [HugoNikanor/reddit-parenthesis-bot#3]
The bot responded to this comment, despite the parenthesis being part of an emoticon: https://www.reddit.com/r/ProgrammerHumor/comments/4ktp12/my_colleague_ran_a_tool_to_document_our_code_base/d3idulq

**Comment by HugoNikanor** [comment]
Emoticon checking works as intended. It however only works for default sad emoticons `:(`. This is possibly an issue, but another one.
