### ISSUE TITLE
Negative depth parenthesis

### ISSUE THREAD

**Issue by dllu** [HugoNikanor/reddit-parenthesis-bot#7]
Currently, the input

```
(()))))((((
```

is counted by `count-paren.sh` as 1. However, `(()))))(((()` is negative depth parentheses which is not valid parentheses.

Instead, perhaps we should ignore orphan close parentheses that do not match any open parentheses. For example the above input should be closed with `))))`.

**Comment by HugoNikanor** [comment]
Fixed. Your pull request is now merged into master.
